"""Initial tables: users, zones, parcels

Revision ID: 859b399c2aa6
Revises: 
Create Date: 2026-01-22 20:05:38.624777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '859b399c2aa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define ENUM types
parcel_status_enum = postgresql.ENUM('pending', 'assigned', 'sorted', 'delivered', name='parcel_status', create_type=False)
user_role_enum = postgresql.ENUM('admin', 'trieur', 'chauffeur', name='user_role', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types first
    parcel_status_enum.create(op.get_bind(), checkfirst=True)
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('parcels', sa.Column('latitude', sa.String(length=50), nullable=True))
    op.add_column('parcels', sa.Column('longitude', sa.String(length=50), nullable=True))
    op.add_column('parcels', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.add_column('parcels', sa.Column('timestamp_dispatch', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parcels', sa.Column('timestamp_sort', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('parcels', 'tracking_no',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('parcels', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    
    # Convert status column to ENUM using raw SQL for PostgreSQL
    op.execute("ALTER TABLE parcels ALTER COLUMN status TYPE parcel_status USING status::parcel_status")
    op.alter_column('parcels', 'status', nullable=False)
    
    op.drop_constraint('parcels_tracking_no_key', 'parcels', type_='unique')
    op.create_index(op.f('ix_parcels_id'), 'parcels', ['id'], unique=False)
    op.create_index(op.f('ix_parcels_tracking_no'), 'parcels', ['tracking_no'], unique=True)
    op.create_foreign_key(None, 'parcels', 'zones', ['zone_id'], ['id'])
    op.create_foreign_key(None, 'parcels', 'users', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'parcels', 'users', ['sorter_id'], ['id'])
    op.drop_column('parcels', 'lon')
    op.drop_column('parcels', 'created_at')
    op.drop_column('parcels', 'lat')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.Enum('admin', 'trieur', 'chauffeur', name='user_role'),
               existing_nullable=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('zones', sa.Column('zone_name', sa.String(length=255), nullable=False))
    op.alter_column('zones', 'geojson_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_unique_constraint(None, 'zones', ['zone_name'])
    op.drop_column('zones', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'zones', type_='unique')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.alter_column('zones', 'geojson_data',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('zones', 'zone_name')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'trieur', 'chauffeur', name='user_role'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.add_column('parcels', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parcels', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('parcels', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_index(op.f('ix_parcels_tracking_no'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_id'), table_name='parcels')
    op.create_unique_constraint(op.f('parcels_tracking_no_key'), 'parcels', ['tracking_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('parcels', 'status',
               existing_type=sa.Enum('pending', 'assigned', 'sorted', 'delivered', name='parcel_status'),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('parcels', 'source',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('parcels', 'tracking_no',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('parcels', 'timestamp_sort')
    op.drop_column('parcels', 'timestamp_dispatch')
    op.drop_column('parcels', 'zone_id')
    op.drop_column('parcels', 'longitude')
    op.drop_column('parcels', 'latitude')
    op.drop_column('parcels', 'address')
    # ### end Alembic commands ###
